name: CI

on:
  pull_request:
  push:
    branches: [ master, test ]

jobs:
  tests-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
