name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.7.0, 10.x, 12.x, 14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Python 2.x
        if: ${{ matrix.node-version == '10.7.0' }}
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'
          update-environment: true
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
  tests-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.7.0, 10.x, 12.x, 14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
  tests-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
